services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama

  ollama-init:
    image: ollama/ollama
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for Ollama...' &&
      until ollama list >/dev/null 2>&1; do
        sleep 2;
      done;
      echo 'Ollama is ready, pulling models...' &&
      ollama pull mistral &&
      ollama pull nomic-embed-text
      "

  pgvector:
    container_name: pgvector
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    volumes:
      - ./volume-data/postgres:/var/lib/postgresql/data

volumes:
  ollama_data: