spring:
  application:
    name: spring-ai-rag-tutorial
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: testuser
    password: testpwd

  jpa:
    hibernate:
      ddl-auto: update

    vectorstore:
      pgvector:
        initialize-schema: true
        table-name: vectordb

server:
  port: 9944

logging:
  level:
    org.springframework.ai.vectorstore: DEBUG